#!/bin/bash
set -e

# Target directories inside flashable payload
mkdir -p flashable_module/zygisk/arm64-v8a
mkdir -p flashable_module/zygisk/armeabi-v7a

# Copy native libraries generated by ndk-build
if [ -f "native/libs/arm64-v8a/libdisable_hdr.so" ]; then
    cp native/libs/arm64-v8a/libdisable_hdr.so flashable_module/zygisk/arm64-v8a.so
fi

if [ -f "native/libs/armeabi-v7a/libdisable_hdr.so" ]; then
    cp native/libs/armeabi-v7a/libdisable_hdr.so flashable_module/zygisk/armeabi-v7a.so
fi

# Package flashable Zip
cd flashable_module
zip -r ../disable-hdr-zygisk.zip . -x "*.DS_Store"
cd ..
